doctype: CRE
id: 871-677
links:
- document:
    description: Verify that anti-automation controls are effective at mitigating
      breached credential testing, brute force, and account lockout attacks. Such
      controls include blocking the most common breached passwords, soft lockouts,
      rate limiting, CAPTCHA, ever increasing delays between attempts, IP address
      restrictions, or risk-based restrictions such as location, first login on a
      device, recent attempts to unlock the account, or similar. Verify that no more
      than 100 failed attempts per hour is possible on a single account.
    doctype: CRE
    id: 001-005-074
    name: ANTI_AUTOMATION_VALIDATE_DETECT_ANOMALIES
  type: SAM
- document:
    description: Verify that the application or framework enforces a strong anti-CSRF
      mechanism to protect authenticated functionality, and effective anti-automation
      or anti-CSRF protects unauthenticated functionality.
    doctype: CRE
    id: 008-047-022
    name: VALIDATE_ORIGIN_CSRF_ANTI_AUTOMATION
  type: SAM
- document:
    description: Verify the application has appropriate limits for specific business
      actions or transactions which are correctly enforced on a per user basis.
    doctype: CRE
    id: 003-004
    name: AUTHORIZE_FUNCTIONS_PER_USER
  type: SAM
- document:
    description: Verify the application has business logic limits or validation to
      protect against likely business risks or threats, identified using threat modelling
      or similar methodologies.
    doctype: CRE
    id: 003-004
    name: VALIDATE_BUSINESS_LOGIC_THREAT_MODEL
  type: SAM
- document:
    description: Verify the application monitors for unusual events or activity from
      a business logic perspective. For example, attempts to perform actions out of
      order or actions which a normal user would never attempt. (C9)
    doctype: CRE
    id: 003-004
    name: MONITOR_ABUSE_BASED_ON_BUSINESS_LOGIC
  type: SAM
- document:
    description: Verify that REST services have anti-automation controls to protect
      against excessive calls, especially if the API is unauthenticated.
    doctype: CRE
    id: 008-004-055
    name: API_ANTI_AUTOMATION
  type: SAM
name: ANTI_AUTOMATION
