description: Verify that the application or framework enforces a strong anti-CSRF
  mechanism to protect authenticated functionality, and effective anti-automation
  or anti-CSRF protects unauthenticated functionality.
doctype: CRE
id: 008-047-022
links:
- document:
    doctype: CRE
    id: 871-677
    name: ANTI_AUTOMATION
  type: SAM
- document:
    doctype: CRE
    id: 769-181
    name: INTERFACE/API
  type: SAM
- document:
    doctype: CRE
    id: 352-435
    name: VALIDATE_ORIGIN
  type: SAM
- document:
    doctype: CRE
    id: 813-481
    name: CSRF
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: SIG ISO 25010
    section: Input and output verification
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: ASVS
    section: V4.2.2
    subsection: INTERFACE/API-VALIDATE_ORIGIN-CSRF-ANTI_AUTOMATION
  type: SAM
- document:
    doctype: Standard
    hyperlink: https://cheatsheetseries.owasp.org/cheatsheets/REST_Assessment_Cheat_Sheet.html
    name: Cheatsheet
    section: Access Control Verification Requirements
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: WSTG
    section: WSTG-SESS-05
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: TOP10
    section: https://owasp.org/www-project-top-ten/2017/A5_2017-Broken_Access_Control
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: CWE
    section: '352'
    subsection: ''
  type: SAM
- document:
    doctype: Standard
    hyperlink: ''
    name: NIST 800-53
    section: CM-6 Configuration Settings
    subsection: ''
  type: SAM
name: VALIDATE_ORIGIN_CSRF_ANTI_AUTOMATION
